In [1]:
import pandas as pd

In [5]:
gp_df = pd.read_csv(
    "../data/processed/GP_Wise_Data.csv",
    dtype={"GP Code": "string"}
)

In [6]:
gp_df.shape

(16323, 113)

In [7]:
gp_df["GP Code"].dtype

In [8]:
gp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16323 entries, 0 to 16322
Columns: 113 entries, Circle to Target for Sept
dtypes: float64(64), int64(5), str(43), string(1)
memory usage: 14.1 MB

In [9]:
gp_df.columns.tolist()

['Circle',
 'BA',
 'DISTRICT',
 'BLOCK',
 'Block Code',
 'New Block Code post BoQ',
 'New Block Name post BoQ',
 'Block Changed',
 'Block HoTo Status',
 'GP',
 'GP Code',
 'LOCATION CODE',
 'Converted to NP & Closed',
 'GP Type',
 'Phase',
 'OLT Location',
 'BBNL Live KM',
 'BSNL Live KM',
 'TOTAL RKM',
 'LMS /AMC Date ',
 'HOTO Date',
 'Lot wise',
 'Letter submission date AMC Incremental',
 'AMC / Incremental',
 'AMC Date',
 'Apr-26',
 'May-26',
 'Jun-26',
 'Jul-26',
 'Aug-26',
 'Sep-26',
 'Oct-26',
 "May'26 (AMC)",
 "Jun'26 (AMC)",
 "Jul'26 (AMC)",
 "Aug'26 (AMC)",
 "Sept'26 (AMC)",
 "Octt'26 (AMC)",
 'W-41',
 'W-40',
 'W-39',
 'W-38',
 'W-37',
 'W-36',
 '1-Sep',
 '2-Sep',
 '3-Sep',
 '4-Sep',
 '5-Sep',
 '6-Sep',
 '7-Sep',
 '8-Sep',
 '9-Sep',
 '10-Sep',
 '11-Sep',
 '12-Sep',
 '13-Sep',
 '14-Sep',
 '15-Sep',
 '16-Sep',
 '17-Sep',
 '18-Sep',
 '19-Sep',
 '20-Sep',
 '21-Sep',
 '22-Sep',
 '23-Sep',
 '24-Sep',
 '25-Sep',
 '26-Sep',
 '27-Sep',
 '28-Sep',
 '29-Sep',
 '30-Sep',
 '1-Oct',
 '2-Oct',
 '3-Oct',
 '4-Oct',
 '5-Oct',
 '6-Oct',
 '7-Oct',
 '8-Oct',
 '9-Oct',
 '10-Oct',
 '11-Oct',
 'April',
 'May',
 'June',
 'July',
 'Aug',
 'Sept',
 'WK-36',
 'WK-37',
 'WK-38',
 'WK-39',
 'WK-40',
 'Till 1 Oct',
 'Till 2 Oct',
 'Till 3 Oct',
 'Till 4 Oct',
 'Till 5 Oct',
 'Unnamed: 101',
 'FRT Code',
 'Name of splicer',
 'Splicer Contact No.',
 'FE Name',
 'FE Contact No',
 'AM Name',
 'AM Contact No',
 'SHQ Spoc ',
 'SHQ Spoc  Contact No',
 'Block Priority',
 'Target for Sept']

In [10]:
for i, col in enumerate(gp_df.columns):
    print(i, "→", repr(col))

0 → 'Circle'
1 → 'BA'
2 → 'DISTRICT'
3 → 'BLOCK'
4 → 'Block Code'
5 → 'New Block Code post BoQ'
6 → 'New Block Name post BoQ'
7 → 'Block Changed'
8 → 'Block HoTo Status'
9 → 'GP'
10 → 'GP Code'
11 → 'LOCATION CODE'
12 → 'Converted to NP & Closed'
13 → 'GP Type'
14 → 'Phase'
15 → 'OLT Location'
16 → 'BBNL Live KM'
17 → 'BSNL Live KM'
18 → 'TOTAL RKM'
19 → 'LMS /AMC Date '
20 → 'HOTO Date'
21 → 'Lot wise'
22 → 'Letter submission date AMC Incremental'
23 → 'AMC / Incremental'
24 → 'AMC Date'
25 → 'Apr-26'
26 → 'May-26'
27 → 'Jun-26'
28 → 'Jul-26'
29 → 'Aug-26'
30 → 'Sep-26'
31 → 'Oct-26'
32 → "May'26 (AMC)"
33 → "Jun'26 (AMC)"
34 → "Jul'26 (AMC)"
35 → "Aug'26 (AMC)"
36 → "Sept'26 (AMC)"
37 → "Octt'26 (AMC)"
38 → 'W-41'
39 → 'W-40'
40 → 'W-39'
41 → 'W-38'
42 → 'W-37'
43 → 'W-36'
44 → '1-Sep'
45 → '2-Sep'
46 → '3-Sep'
47 → '4-Sep'
48 → '5-Sep'
49 → '6-Sep'
50 → '7-Sep'
51 → '8-Sep'
52 → '9-Sep'
53 → '10-Sep'
54 → '11-Sep'
55 → '12-Sep'
56 → '13-Sep'
57 → '14-Sep'
58 → '15-Sep'
59 → '16-Sep'
60 → '17-Sep'
61 → '18-Sep'
62 → '19-Sep'
63 → '20-Sep'
64 → '21-Sep'
65 → '22-Sep'
66 → '23-Sep'
67 → '24-Sep'
68 → '25-Sep'
69 → '26-Sep'
70 → '27-Sep'
71 → '28-Sep'
72 → '29-Sep'
73 → '30-Sep'
74 → '1-Oct'
75 → '2-Oct'
76 → '3-Oct'
77 → '4-Oct'
78 → '5-Oct'
79 → '6-Oct'
80 → '7-Oct'
81 → '8-Oct'
82 → '9-Oct'
83 → '10-Oct'
84 → '11-Oct'
85 → 'April'
86 → 'May'
87 → 'June'
88 → 'July'
89 → 'Aug'
90 → 'Sept'
91 → 'WK-36'
92 → 'WK-37'
93 → 'WK-38'
94 → 'WK-39'
95 → 'WK-40'
96 → 'Till 1 Oct'
97 → 'Till 2 Oct'
98 → 'Till 3 Oct'
99 → 'Till 4 Oct'
100 → 'Till 5 Oct'
101 → 'Unnamed: 101'
102 → 'FRT Code'
103 → 'Name of splicer'
104 → 'Splicer Contact No.'
105 → 'FE Name'
106 → 'FE Contact No'
107 → 'AM Name'
108 → 'AM Contact No'
109 → 'SHQ Spoc '
110 → 'SHQ Spoc  Contact No'
111 → 'Block Priority'
112 → 'Target for Sept'

In [11]:
gp_df["GP Code"].nunique()

16323

In [12]:
gp_df["GP Code"].isna().sum()

np.int64(0)

In [13]:
gp_df["GP Code"].duplicated().sum()

np.int64(0)

In [14]:
gp_df["Circle"].value_counts(dropna=False)

Circle
RAJASTHAN    8746
HARYANA      6082
ASSAM        1495
Name: count, dtype: int64

In [15]:
gp_df["GP Type"].value_counts(dropna=False)

GP Type
Existing    16323
Name: count, dtype: int64

In [16]:
gp_df["Block HoTo Status"].value_counts(dropna=False)

Block HoTo Status
Done    15978
NaN       345
Name: count, dtype: int64

In [18]:
import sys
sys.path.append("../")

In [19]:
from src.data_cleaning import load_data, clean_data

In [20]:
file_path = "../data/processed/GP_Wise_Data.csv"

gp_df = load_data(file_path)
cleaned_df = clean_data(gp_df)

In [21]:
cleaned_df.shape

(16323, 113)

In [22]:
cleaned_df.columns.tolist()

['circle',
 'ba',
 'district',
 'block',
 'block_code',
 'new_block_code_post_boq',
 'new_block_name_post_boq',
 'block_changed',
 'block_hoto_status',
 'gp',
 'gp_code',
 'location_code',
 'converted_to_np_&_closed',
 'gp_type',
 'phase',
 'olt_location',
 'bbnl_live_km',
 'bsnl_live_km',
 'total_rkm',
 'lms__amc_date',
 'hoto_date',
 'lot_wise',
 'letter_submission_date_amc_incremental',
 'amc___incremental',
 'amc_date',
 'apr-26',
 'may-26',
 'jun-26',
 'jul-26',
 'aug-26',
 'sep-26',
 'oct-26',
 "may'26_(amc)",
 "jun'26_(amc)",
 "jul'26_(amc)",
 "aug'26_(amc)",
 "sept'26_(amc)",
 "octt'26_(amc)",
 'w-41',
 'w-40',
 'w-39',
 'w-38',
 'w-37',
 'w-36',
 '1-sep',
 '2-sep',
 '3-sep',
 '4-sep',
 '5-sep',
 '6-sep',
 '7-sep',
 '8-sep',
 '9-sep',
 '10-sep',
 '11-sep',
 '12-sep',
 '13-sep',
 '14-sep',
 '15-sep',
 '16-sep',
 '17-sep',
 '18-sep',
 '19-sep',
 '20-sep',
 '21-sep',
 '22-sep',
 '23-sep',
 '24-sep',
 '25-sep',
 '26-sep',
 '27-sep',
 '28-sep',
 '29-sep',
 '30-sep',
 '1-oct',
 '2-oct',
 '3-oct',
 '4-oct',
 '5-oct',
 '6-oct',
 '7-oct',
 '8-oct',
 '9-oct',
 '10-oct',
 '11-oct',
 'april',
 'may',
 'june',
 'july',
 'aug',
 'sept',
 'wk-36',
 'wk-37',
 'wk-38',
 'wk-39',
 'wk-40',
 'till_1_oct',
 'till_2_oct',
 'till_3_oct',
 'till_4_oct',
 'till_5_oct',
 'unnamed:_101',
 'frt_code',
 'name_of_splicer',
 'splicer_contact_no.',
 'fe_name',
 'fe_contact_no',
 'am_name',
 'am_contact_no',
 'shq_spoc',
 'shq_spoc__contact_no',
 'block_priority',
 'target_for_sept']

In [23]:
[col for col in cleaned_df.columns if any(
    keyword in col
    for keyword in ["hoto", "amc", "availability", "rkm", "frt", "uptime", "one", "target"]
)]

['block_hoto_status',
 'total_rkm',
 'lms__amc_date',
 'hoto_date',
 'letter_submission_date_amc_incremental',
 'amc___incremental',
 'amc_date',
 "may'26_(amc)",
 "jun'26_(amc)",
 "jul'26_(amc)",
 "aug'26_(amc)",
 "sept'26_(amc)",
 "octt'26_(amc)",
 'frt_code',
 'target_for_sept']

In [25]:
amc_gps = cleaned_df["amc_date"].notna().sum()
amc_gps

np.int64(6664)

In [26]:
existing_gps = (cleaned_df["gp_type"] == "Existing").sum()
existing_gps

np.int64(16323)

In [27]:
cleaned_df.groupby("circle")["gp_code"].nunique()

circle
ASSAM        1495
HARYANA      6082
RAJASTHAN    8746
Name: gp_code, dtype: int64

In [28]:
cleaned_df["converted_to_np_&_closed"].value_counts(dropna=False)

converted_to_np_&_closed
NaN                                            15987
Converted to Nagar Palika                        321
GP deduction from Block during portal entry       15
Name: count, dtype: int64

In [29]:
cleaned_df.groupby(
    "circle"
)["converted_to_np_&_closed"].apply(
    lambda x: x.isna().sum()
)

circle
ASSAM        1480
HARYANA      6082
RAJASTHAN    8425
Name: converted_to_np_&_closed, dtype: int64

In [30]:
assam = cleaned_df[cleaned_df["circle"] == "ASSAM"]

assam[
    assam["converted_to_np_&_closed"].isna()
][["gp", "gp_code", "block", "converted_to_np_&_closed"]].head(20)

                  gp gp_code         block converted_to_np_&_closed
276          Jengrai  106680  Ujani Majuli                      NaN
277       Luit Poria  106681  Ujani Majuli                      NaN
278          Phuloni  106682  Ujani Majuli                      NaN
279         Ratanpur  106683  Ujani Majuli                      NaN
280       Rangachahi  106684  Ujani Majuli                      NaN
281   Ratanpur Gayan  106685  Ujani Majuli                      NaN
282          Cherpai  106686  Ujani Majuli                      NaN
283           Sriram  106687  Ujani Majuli                      NaN
284          Banmukh  107499     Sivasagar                      NaN
285          Betbari  107500     Sivasagar                      NaN
286        Chaulkara  107501     Sivasagar                      NaN
287       Cherekapar  107502     Sivasagar                      NaN
288  Desang Dhai Ali  107503     Sivasagar                      NaN
289       Desangmukh  107504     Sivasagar                      NaN
290        Desangpar  107505     Sivasagar                      NaN
291          Gargaon  107506     Sivasagar                      NaN
292         Hahchora  107507     Sivasagar                      NaN
293           Khelua  107508     Sivasagar                      NaN
294        Konwarpur  107509     Sivasagar                      NaN
295           Lachit  107510     Sivasagar                      NaN

In [31]:
assam = cleaned_df[cleaned_df["circle"] == "ASSAM"]

assam["converted_to_np_&_closed"].value_counts(dropna=False)

converted_to_np_&_closed
NaN                                            1480
GP deduction from Block during portal entry      15
Name: count, dtype: int64

In [32]:
gp_type == "Existing" & converted_to_np_closed.isna()

NameError: name 'gp_type' is not defined

In [33]:
cleaned_df[
    (cleaned_df["gp_type"] == "Existing") &
    (cleaned_df["converted_to_np_&_closed"].isna())
].shape[0]

15987

In [34]:
assam = cleaned_df[cleaned_df["circle"] == "ASSAM"]

assam[
    (assam["gp_type"] == "Existing") &
    (assam["converted_to_np_&_closed"].isna())
].shape[0]

1480

In [35]:
assam_blank = assam[
    (assam["gp_type"] == "Existing") &
    (assam["converted_to_np_&_closed"].isna())
]

assam_blank["block_hoto_status"].value_counts(dropna=False)

block_hoto_status
Done    1470
NaN       10
Name: count, dtype: int64

In [36]:
assam_blank[
    assam_blank["block_hoto_status"].isna()
][[
    "gp",
    "gp_code",
    "block",
    "block_hoto_status",
    "converted_to_np_&_closed"
]]

,gp,gp_code,block,block_hoto_status,converted_to_np_&_closed
16001,Paschim Howly,261123,Gobardhana,NaN,NaN
16089,Rajnagar,105897,Salchapra,NaN,NaN
16090,Berenga,105901,Silchar,NaN,NaN
16091,Bhajantipur,105903,Silchar,NaN,NaN
16092,Ghungoor,105904,Silchar,NaN,NaN
16093,Madhurbond,105906,Silchar,NaN,NaN
16094,Meherpur,105907,Silchar,NaN,NaN
16095,Tarapur,105910,Silchar,NaN,NaN
16196,Shernagar,106095,Agomani,NaN,NaN
16197,Sundarpara,106186,Jamadarhat,NaN,NaN

In [37]:
assam_blank[
    assam_blank["block_hoto_status"].isna()
][[
    "gp",
    "gp_code",
    "block",
    "gp_type",
    "block_changed",
    "gp_type",
    "phase",
    "amc_date",
    "hoto_date"
]]

,gp,gp_code,block,gp_type,block_changed,gp_type,phase,amc_date,hoto_date
16001,Paschim Howly,261123,Gobardhana,Existing,No,Existing,Phase-1,NaN,NaN
16089,Rajnagar,105897,Salchapra,Existing,No,Existing,Phase-1,NaN,NaN
16090,Berenga,105901,Silchar,Existing,No,Existing,Phase-1,NaN,NaN
16091,Bhajantipur,105903,Silchar,Existing,No,Existing,Phase-1,NaN,NaN
16092,Ghungoor,105904,Silchar,Existing,No,Existing,Phase-1,NaN,NaN
16093,Madhurbond,105906,Silchar,Existing,No,Existing,Phase-1,NaN,NaN
16094,Meherpur,105907,Silchar,Existing,No,Existing,Phase-1,NaN,NaN
16095,Tarapur,105910,Silchar,Existing,No,Existing,Phase-1,NaN,NaN
16196,Shernagar,106095,Agomani,Existing,No,Existing,Phase-1,NaN,NaN
16197,Sundarpara,106186,Jamadarhat,Existing,No,Existing,Satellite,NaN,NaN

In [38]:
(
    (cleaned_df["gp_type"] == "Existing") &
    (cleaned_df["converted_to_np_&_closed"].isna())
).sum()

np.int64(15987)

In [39]:
hoto_done_gps = (
    cleaned_df["block_hoto_status"] == "Done"
).sum()

hoto_done_gps

np.int64(15978)

In [40]:
hoto_percentage = (
    hoto_done_gps / 15978
) * 100

hoto_percentage

np.float64(100.0)

In [41]:

amc_gps = cleaned_df["amc_date"].notna().sum()

amc_gps

np.int64(6664)

In [42]:
amc_percentage = (
    amc_gps / 15978
) * 100

amc_percentage

np.float64(41.70734760295406)

In [43]:
cleaned_df.columns[
    cleaned_df.columns.str.contains("rkm|fibre|fiber", case=False)
]

Index(['total_rkm'], dtype='str')

In [44]:
cleaned_df.groupby("amc_date")["total_rkm"].sum()

amc_date
5-1-2026      9804.0
5-13-2026       81.0
5-16-2026       19.0
5-18-2026      691.0
5-25-2026    11029.0
5-27-2026      287.0
5-30-2026       21.0
6-10-2026       34.0
6-11-2026      351.0
6-12-2026      138.0
6-16-2026      166.0
6-18-2026       69.0
6-19-2026       88.0
6-23-2026      118.0
6-24-2026      366.0
6-25-2026      120.0
6-29-2026      328.0
7-1-2026       391.0
7-16-2026     3762.0
7-17-2026       98.0
7-20-2026      239.0
7-21-2026      343.0
7-22-2026      130.0
7-30-2026       32.0
7-31-2026        8.0
7-7-2026       235.0
7-8-2026        37.0
7-9-2026        69.0
8-12-2026        2.0
8-13-2026       17.0
8-18-2026       87.0
8-19-2026      149.0
8-20-2026      110.0
8-24-2026       21.0
8-25-2026       16.0
8-26-2026       19.0
8-27-2026       85.0
8-28-2026       45.0
8-31-2026     3742.0
8-7-2026       383.0
9-10-2026      474.0
9-14-2026       17.0
9-18-2026      132.0
9-19-2026      204.0
9-25-2026       23.0
9-28-2026       50.0
9-3-2026       639.0
9-30-2026      237.0
9-8-2026       395.0
Name: total_rkm, dtype: float64

In [46]:
amc_rkm = cleaned_df.loc[
    cleaned_df["amc_date"].notna(),
    "total_rkm"
].sum()

amc_rkm

np.float64(35901.0)

In [47]:
cleaned_df.loc[
    cleaned_df["amc_date"].notna()
].groupby("circle")["total_rkm"].sum()

circle
ASSAM          359.0
HARYANA       5915.0
RAJASTHAN    29627.0
Name: total_rkm, dtype: float64

In [48]:
cleaned_df[
    ["bbnl_live_km", "bsnl_live_km", "total_rkm"]
].sum()

bbnl_live_km    43578.34
bsnl_live_km    40214.93
total_rkm       83718.30
dtype: float64